Traceback (most recent call last):
  File "/home/ubuntu/ros2_ws/build/champ_bringup/ament_cmake_python/champ_bringup/setup.py", line 1, in <module>
    from setuptools import find_packages
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.10/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3278, in _initialize_master_working_set
    list(map(working_set.add_entry, sys.path))
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 608, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2063, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2128, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2591, in from_location
    )._reload_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2989, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2770, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2554, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2765, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1417, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1407, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1611, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/ros2_ws/install/mini_pupper_music/lib/python3.10/site-packages/mini_pupper_music-1.0.0-py3.10.egg-info/PKG-INFO'
gmake[2]: *** [CMakeFiles/ament_cmake_python_build_champ_bringup_egg.dir/build.make:70: CMakeFiles/ament_cmake_python_build_champ_bringup_egg] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/ament_cmake_python_build_champ_bringup_egg.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
